import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Header from '@/components/navigation/header/Header';
import Footer from '@/components/navigation/footer/Footer';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>NextJs Fullstack App Template</title>
      </Head>
      <body className={inter.className}>
        <div className={`min-h-screen flex flex-col items-center`}>
          <Header />
          <main className="px-5">{children}</main>
          <div className="m-auto" />
          <Footer />
        </div>
      </body>
    </html>
  );
}
